version: '2.0'

services:
  web:
    build: .
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /bundle_cache
      - /etc/letsencrypt/live/postitapp.tk/fullchain.pem:/etc/letsencrypt/live/postitapp.tk/fullchain.pem
      - /etc/letsencrypt/live/postitapp.tk/privkey.pem:/etc/letsencrypt/live/postitapp.tk/privkey.pem
